### ISSUE TITLE
Ship shouldn't be able to go outside the screen

### ISSUE THREAD

**Issue by sebbe33** [Jokab/Bullet-Inferno#22]

**Comment by Jokab** [comment]
Lösningen på detta 1faa3626b4bc4e14f8d5086fab1682660395ecb3, är kanske inte den bästa. Ska playern hålla reda på hur stor världen är?

**Comment by joelseverin** [comment]
Det är inte snyggt, men modellerna känner till viewporten på världen för att kunna sätta sig inom den (+lite optimeringar). Finns setViewport i EntityEnvironment (eller möjligen bara MapEnv...) tror jag, som kommer från ModelEnvironment... Annars kan man stoppa constrainten i controllern, så att man aldrig sätter positionen fel. Kanske bättre här om det funkar =)

**Comment by Jokab** [comment]
Mm okej, håller med. Closar denna igen då.
