### ISSUE TITLE
Slices sometimes get separated creating a white line between them.

### ISSUE THREAD

**Issue by verath** [Jokab/Bullet-Inferno#28]
When the slices are moved they seem to sometimes end up in a position where the end of one slice is about a pixel "ahead" of the start of the next slice. This creates a line displaying the white background.

Could possibly be fixed by adding a small "padding" to the slices (i.e. making the images a few pixel wider than the slice "should" be). Or maybe we could overlay the slices slightly on top of one another (i.e. making the next slice start before the last slice ends).

**Comment by joelseverin** [comment]
This issue occured for me the first time now!
