### ISSUE TITLE
Score should not increase while fighting boss

### ISSUE THREAD

**Issue by Jokab** [Jokab/Bullet-Inferno#35]
Because if it does, it's better for your score to not fight the boss, which is not what we want.

**Comment by marcjamot** [comment]
Tycker nästan att den borde öka även på boss då det är "tid du lyckas överleva", som är ännu svårare på en boss. Däremot borde skillnaden var mycket mer märkbar mellan tid passerad och fiender dödade.. t ex:
10 score per sekund
100 -> 600 score för fiender
8000 -> 15000 score för boss

**Comment by Jokab** [comment]
Å andra sidan så borde väl bossen vara ett hinder som gör att man inte kan få poäng längre. I teorin skulle man kunna bara stå på bossen och få poäng i all evighet, om man är tillräckligt duktig på att undvika dess skott, vilket jag tror inte är vår kollektiva avsikt. Håller dock med om att man borde få mer poäng för att döda fiender i relation till score/sek.
