### ISSUE TITLE
Segment slice-randomizer fails randomly

### ISSUE THREAD

**Issue by joelseverin** [Jokab/Bullet-Inferno#5]
The problem seems to occur when:
- Generating the first middle-slice (0 in the loop).
- The segment fails to be paired with the entry-slice.

Getting the exception for "no path found".

**Comment by Jokab** [comment]
Är den fixad alltså? Hur?

**Comment by verath** [comment]
Tror inte det var en bug utan snarare att segmentet WATER inte gick att skapa för vissa värden av "antal slices". Det är  meningen att den ska faila då, och (tror jag) upp till den som "designar" segmenten att se till att det alltid går. Alternativt upp till den som skapar segment att inte skapa segment som inte kommer gå att skapa.
